import Head from "next/head";
import { motion } from "framer-motion";
import { BsMoonStarsFill } from "react-icons/bs";
// import { fadeIn } from './varients';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import deved from "../public/dev-ed-wave.png";
import Image from "next/image";
import fullstack11 from "../public/assets/Certification/fullstack11.jpg"
import JB from "../public/assets/Certification/JB.png";
import html03 from "../public/assets/Certification/html03.jpg"
import html05 from "../public/assets/Certification/html05.jpg"
import reactIcon from "../public/assets/react.png";
import jsIcon from "../public/assets/javascript.png";
import css01 from "../public/assets/Certification/css01.jpg"
import html01 from "../public/assets/Certification/html01.jpg"
import html04 from "../public/assets/Certification/html04.jpg"
import css02 from "../public/assets/Certification/css02.jpg"
import js01 from "../public/assets/Certification/js01.jpg"
import js02 from "../public/assets/Certification/js02.jpg"
import react01 from "../public/assets/Certification/react01.jpg"
import react02 from "../public/assets/Certification/react02.jpg"
import p1 from "../public/assets/Certification/p1.jpg"
import p2 from "../public/assets/Certification/p2.jpg"
import i1 from "../public/assets/Certification/i1.jpg"
import i2 from "../public/assets/Certification/i2.jpg"

import cssIcon from "../public/assets/css.png";
import PDFPC from "../public/assets/Certification/PDFPC.jpg";
import tailwindIcon from "../public/assets/tailwind.png";
import PSB from "../public/assets/Certification/PSB.png";
import KP from "../public/assets/Certification/KP.png";
import JI from "../public/assets/Certification/JI.png";
import GAFB from "../public/assets/Certification/GAFB.jpg";
import FODM from "../public/assets/Certification/FODM.jpg";
import htmlIcon from "../public/assets/html.png";
import sql from "../public/assets/sql.png";
import java from "../public/assets/java1.png";
import LCSS from "../public/assets/Certification/LCSS.png";
import IHC from "../public/assets/Certification/IHC.png";
import CSS from "../public/assets/Certification/CSS.jpg";
import firestore from "../public/assets/firestore1.png";
import PB from "../public/assets/Certification/PB.jpg";
import SI from "../public/assets/Certification/SI.png";
import githubIcon from "../public/assets/github.png";
import youtube from "../public/assets/youtube.png";
import fullstack from "../public/assets/Certification/fullstack.jpg";
import c from "../public/assets/Certification/c.jpg";
import c00 from "../public/assets/Certification/c00.jpg";
import RB from "../public/assets/Certification/RB.png";
import insta from "../public/assets/insta.png";
import food from "../public/assets/food.png";
import portfolio from "../public/assets/portfolio.png";
import ED from "../public/assets/Certification/ED.jpg";
import SB from "../public/assets/Certification/SB.png";
import { useState } from "react";
import Typewriter from "typewriter-effect";
import { FaHome } from "react-icons/fa";
import { FaTools } from "react-icons/fa";
import { BsFillRocketTakeoffFill } from "react-icons/bs";

import { Link } from "react-scroll";
import { MdEmail } from "react-icons/md";
import { SiLeetcode } from "react-icons/si";
import { BsGithub } from "react-icons/bs";

export const fadeIn = (direction, delay) => {
  return {
    hidden: {
      y: direction === "up" ? 80 : direction === "down" ? -80 : 0,
      opacity: 0,
      x: direction === "left" ? 80 : direction === "right" ? -80 : 0,
    },
    show: {
      y: 0,
      x: 0,
      opacity: 1,
      transition: {
        type: "tween",
        duration: 1.2,
        delay: delay,
        ease: [0.25, 0.25, 0.25, 0.75],
      },
    },
  };
};

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>MyProfile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20  lg:px-32 dark:bg-black">
        <section id="home" className="min-h-screen ">
          {/* navbar - 1 */}
          <nav className=" flex justify-between py-10 mb-12">
            <h1 className="text-xl font-burtons dark:text-white">
              developedbyme
            </h1>
            <ul className="flex items-center">
              <li>
                <BsMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-xl dark:text-white "
                />
              </li>
              {/* <li className='ml-4 bg-gradient-to-r from-cyan-500 to-teal-500 text-white rounded px-4 py-1'><a href='#'>Resume </a> </li> */}
              <li className="ml-4 bg-gradient-to-r from-cyan-500 to-teal-500 text-white rounded px-4 py-1">
                <a
                  href="https://drive.google.com/file/d/1vpP7Jp1GYzAtZF4pRlLF-s_SeprU4TyT/view?usp=share_link"
                  download="Resume"
                  target="_blank"
                >
                  Resume
                </a>{" "}
              </li>
            </ul>
          </nav>
          {/* some about text */}
          <div className=" text-center p-10">
            <h2 className="text-4xl py-2 text-teal-600 font-medium md:text-6xl">
              Shaheen Parveen
            </h2>

            {/* typewritter effect */}

            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              <Typewriter
                options={{
                  strings: [
                    "I am a frontend developer",
                    "I love❤️ to build Desigin ",
                  ],
                  autoStart: true,
                  loop: true,
                }}
              />
            </h3>
            <p className="py-5 leading-8 text-gray-800 max-w-xl mx-auto dark:text-gray-400">
              Hello I'm a Frontend developer providing services for programming
              and design content needs. Join me down below and let's get
              cracking!
            </p>
          </div>
          <div className="text-5xl flex   justify-center gap-16 text-gray-600 dark:text-gray-300 ">
            <a href="mailto:shaheenparveen871215@gmail.com" target="_blank">
              <MdEmail />
            </a>
            <a
              href="https://www.linkedin.com/in/shaheen-parveen/"
              target="_blank"
            >
              <AiFillLinkedin />
            </a>
            <a href="https://leetcode.com/shaheenparveen/" target="_blank">
              <SiLeetcode />
            </a>
            <a href="https://github.com/SHAHEEN2004" target="_blank">
              <BsGithub />
            </a>
          </div>
          <div className="bg-gradient-to-b from-teal-500  my-5 rounded-full relative w-80 h-80 mt-20 mx-auto  overflow-hidden md:w-96 md:h-96">
            <Image src={deved} fill alt="deved_icon" />
          </div>
        </section>

        <section id="skill">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Skills </h3>
          </div>
          <div className="my-10 flex flex-wrap lg:flex gap-5 lg:justify-center">
            <div
              title="React"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1  my-5 py-4 text-center flex flex-col items-center   shadow-lg rounded-xl  dark:shadow-blue-300"
            >
              <Image
                className="my-4"
                src={reactIcon}
                width={100}
                height={100}
              />
            </div>
            <div
              title="Javascript"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-yellow-300"
            >
              <Image
                className="my-4 rounded-xl"
                src={jsIcon}
                width={100}
                height={100}
              />
            </div>
            <div
              title="HTML5"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-orange-400"
            >
              <Image className="my-4" src={htmlIcon} width={100} height={100} />
            </div>
            <div
              title="CSS3"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-blue-400"
            >
              <Image className="my-4" src={cssIcon} width={100} height={100} />
            </div>
            <div
              title="SQL"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-orange-300"
            >
              <Image
                className="my-4 rounded-xl"
                src={sql}
                width={100}
                height={100}
              />
            </div>
            <div
              title="Python"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-blue-300"
            >
              <Image
                className="my-4 rounded-xl"
                src={java}
                width={100}
                height={100}
              />
            </div>
            <div
              title="Firestore"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-yellow-400"
            >
              <Image
                className="my-4 rounded-xl"
                src={firestore}
                width={100}
                height={100}
              />
            </div>
          </div>
        </section>
        <section id="project" className="pb-20">
          <div className="mb-4">
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <motion.div
              variants={fadeIn("right", "0.3")}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: "0.3" }}
              className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
            >
              <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
              <Image
                src={insta}
                className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
              />
              <a href="https://my-crypto-trackers.netlify.app/" target="_blank">
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/3 z-40 group-hover:bottom-1/2 transition-all duration-500">
                  Live
                </div>
              </a>
              <a
                href="https://github.com/SHAHEEN2004/Crypto-Tracker.git"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-2/3 z-40 group-hover:bottom-1/2  transition-all duration-700">
                  Code{" "}
                </div>
              </a>
            </motion.div>
            <motion.div
              variants={fadeIn("left", "0.3")}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: "0.3" }}
              className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
            >
              <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
              <Image
                src={youtube}
                className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
              />
              <a href="https://bookfinder2.netlify.app" target="_blank">
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/3 z-40 group-hover:bottom-1/2 transition-all duration-500">
                  Live
                </div>
              </a>
              <a
                href="https://github.com/SHAHEEN2004/Book-Finder"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-2/3 z-40 group-hover:bottom-1/2  transition-all duration-700">
                  Code{" "}
                </div>
              </a>
            </motion.div>
            <motion.div
              variants={fadeIn("right", "0.3")}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: "0.3" }}
              className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
            >
              <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
              <Image
                src={food}
                className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
              />
              <a href="https://ours-sound-cloud.netlify.app" target="_blank">
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/3 z-40 group-hover:bottom-1/2 transition-all duration-500">
                  Live
                </div>
              </a>
              <a href="" target="_blank">
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-2/3 z-40 group-hover:bottom-1/2  transition-all duration-700">
                  Code{" "}
                </div>
              </a>
            </motion.div>
            <motion.div
              variants={fadeIn("left", "0.3")}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: "0.3" }}
              className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
            >
              <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
              <Image
                src={portfolio}
                className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
              />
              <a href="https://shaheenparveen.netlify.app/ " target="_blank">
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/3 z-40 group-hover:bottom-1/2 transition-all duration-500">
                  Live
                </div>
              </a>
              <a
                href="https://github.com/SHAHEEN2004/My-Profile-.git"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-2/3 z-40 group-hover:bottom-1/2  transition-all duration-700">
                  Code{" "}
                </div>
              </a>
            </motion.div>
          </div>
        </section>
        <hr></hr>
        <section>










          {/* certifications */}










          <section id="project" className="pb-20">
            <div className="mb-4 ">
              <h3 className="text-3xl py-1 dark:text-white  text-align: center;" >Certifications</h3>
            </div>
            
            <div className="mb-4">
              <h3 className="text-3xl py-1 dark:text-white "> Full Stack & Front-End </h3>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <motion.div
                variants={fadeIn("right", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={fullstack}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/1Nv_G2E0y5deHawFI2vzIiuD02zzol-_M/view?usp=share_link"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>
              <motion.div
                variants={fadeIn("left", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={fullstack11}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/1otv3Ca1kvK0z7UQ4ZaQgRcfLueSS2Pin/view?usp=sharing"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{"  "}
                  </div>
                </a>
              </motion.div>

              
            </div>

            <hr></hr>








            

            {/* NEXT LINE 2 */}
            
            <div className="mb-4">
              <h3 className="text-3xl py-1 dark:text-white ">Html </h3>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <motion.div
                variants={fadeIn("right", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={html01}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/1owCdWsUu8_oygI1s1HAozxaAIo10HSxM/view?usp=sharing"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>
              <motion.div
                variants={fadeIn("left", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={html04}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/1ifOSk2nsmwmmMRJnkWZTQ6vOMSgW3DuG/view?usp=sharing"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>

              
            </div>














            {/* NEXT LINE 3 */}

            
            <div className="mb-4">
              <h3 className="text-3xl py-1 dark:text-white ">CSS </h3>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <motion.div
                variants={fadeIn("right", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={css01}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/1DDQLRRzFav-_xi6f9e2JSO0GoHulq2kC/view?usp=share_link"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>
              <motion.div
                variants={fadeIn("left", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={css02}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/1PXv-04fVahgxLETAMsT3jgU9I3X-8AAB/view?usp=share_link"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>
              

              
            </div>
            {/* NEXT LINE 4 */}









            <div className="mb-4">
              <h3 className="text-3xl py-1 dark:text-white ">JavaScript </h3>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <motion.div
                variants={fadeIn("right", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={js02}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/196iEsLJhSf39M2SLz1bJF1-iLYs9TzVI/view?usp=share_link"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>
              <motion.div
                variants={fadeIn("left", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={js01}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/1kCrxUzorgXDCzOX8-gE7P1qICOQZJFL2/view?usp=sharing"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>

              
            </div>












            {/* NEXT LINE 5 */}



            <div className="mb-4">
              <h3 className="text-3xl py-1 dark:text-white ">React </h3>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <motion.div
                variants={fadeIn("right", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={react01}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/1M2FRAiWhFiHWwTLMBh7TJQoD5w0KNUPE/view?usp=share_link"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>
              <motion.div
                variants={fadeIn("left", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={react02}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/13aSy4e3s2c6Q8gRgcA331JHN0svcRYhO/view?usp=sharing"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>

              
            </div>
            {/* NEXT LINE 5 */}











            <div className="mb-4">
              <h3 className="text-3xl py-1 dark:text-white ">C </h3>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <motion.div
                variants={fadeIn("right", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={c00}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/1ZMM371sccfgNl9scBqokP-m4fZTslOZK/view?usp=sharing"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>
              <motion.div
                variants={fadeIn("left", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={c}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/1PXv-04fVahgxLETAMsT3jgU9I3X-8AAB/view?usp=share_link"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>
              

              
            </div>
            {/* NEXT LINE 6 */}





            <div className="mb-4">
              <h3 className="text-3xl py-1 dark:text-white ">Python </h3>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <motion.div
                variants={fadeIn("right", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={p1}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/1BeyO9BttrMb2XWWLplHHRLnqpuKrC-6Q/view"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>
              <motion.div
                variants={fadeIn("left", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={p2}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/1RH2-vZJd3OVUjXAZ68eyomIoyMlASPBJ/view"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>
              

              
            </div>
            {/* NEXT LINE 7 */}
            <div className="mb-4">
              <h3 className="text-3xl py-1 dark:text-white ">Internships </h3>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <motion.div
                variants={fadeIn("right", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={i1}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://www.pantechelearning.com/APR23/PEL_DS_Part04_0890.pdf"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>
              <motion.div
                variants={fadeIn("left", "0.3")}
                initial="hidden"
                whileInView="show"
                viewport={{ once: false, amount: "0.3" }}
                className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-blue-400"
              >
                <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
                <Image
                  src={i2}
                  className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
                />
                <a
                  href="https://drive.google.com/file/d/18utAlOeT61xngh17iNAAeeNQgHrzNbs7/view"
                  target="_blank"
                >
                  <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2  transition-all duration-700">
                    Open{" "}
                  </div>
                </a>
              </motion.div>

              
            </div>
          </section>
          <section></section>
          <nav className="fixed left-0 bottom-4 lg:bottom-8 w-full overflow-hidden z-50 ">
            <div className="mx-auto w-80 bg-black/10 h-12 backdrop-blur-sm rounded-3xl flex justify-between ">
              <Link
                to="home"
                smooth={true}
                activeClass="active"
                spy={true}
                className=" flex items-center px-2 mx-8 text-2xl cursor-pointer dark:border-white"
              >
                <FaHome className="dark:text-white" />
              </Link>
              <Link
                to="skill"
                smooth={true}
                activeClass="active"
                spy={true}
                className=" flex items-center px-2 mx-8 text-2xl cursor-pointer dark:border-white "
              >
                <FaTools className="dark:text-white" />
              </Link>
              <Link
                to="project"
                smooth={true}
                activeClass="active"
                spy={true}
                className=" flex items-center px-2 mx-8 text-2xl cursor-pointer dark:border-white"
              >
                <BsFillRocketTakeoffFill className="dark:text-white" />
              </Link>
            </div>
          </nav>
        </section>
      </main>
    </div>
  );
}
